/**
 * Guards the app's reliance on the pure-JS `bcryptjs` for password hashing.
 *
 * `bcryptjs` is pure JavaScript with no native build step, so it installs and
 * runs identically on any Node host (Vercel, a plain `next start`, CI, tests).
 * Every route that hashes or verifies passwords uses it instead of the native
 * `bcrypt` addon. The risk this test defends against is not
 * that the swap breaks newly-written hashes — it is that it silently makes
 * the hashes ALREADY IN THE DATABASE unverifiable, which would lock every
 * existing user out.
 *
 * So this file asserts two things:
 *
 *   1. Structurally, that no route imports native `bcrypt` and that the
 *      dependency is gone from `package.json`.
 *   2. Behaviourally, that `bcryptjs` can verify `$2a$`/`$2b$` hashes that
 *      were produced by the reference bcrypt implementation. The canonical
 *      jBCrypt/bcrypt test vectors below are generated by a native build, and
 *      the real fixture hash in `data/users.sql` is what seeded this app's
 *      database. If bcryptjs stops agreeing with either, existing passwords
 *      stop working.
 */
import { readFileSync, existsSync } from "node:fs";
import { test } from "node:test";
import assert from "node:assert/strict";
import bcrypt from "bcryptjs";

const ROUTES = [
  "src/app/api/delete-account/route.js",
  "src/app/api/profile/update/route.js",
  "src/app/api/sync-user/route.ts",
  "src/app/api/webhooks/clerk/route.js",
];

const read = (p) => readFileSync(p, "utf8");

// Hashes produced by the REFERENCE bcrypt implementation, taken from the
// jBCrypt test suite. Each pairs with the plaintext next to it.
const REFERENCE_VECTORS = [
  ["", "$2a$06$DCq7YPn5Rq63x1Lad4cll.TV4S6ytwfsfvkgY8jIucDrjc8deX1s."],
  ["a", "$2a$06$m0CrhHm10qJ3lXRY.5zDGO3rS2KdeeWLuGmsfGlMfOxih58VYVfxe"],
  ["abc", "$2a$06$If6bvum7DFjUnE9p2uDeDu0YHzrHM6tf.iqN8.yx.jNN1ILEf7h0i"],
  [
    "abcdefghijklmnopqrstuvwxyz",
    "$2a$06$.rCVZVOThsIa97pEDOxvGuRRgzG64bvtJ0938xuqzv18d3ZpQhstC",
  ],
];

// The real seed hash in data/users.sql — a $2b$ hash at cost 10.
const FIXTURE_HASH =
  "$2b$10$J8WwxtzvXy0JIQ1YgkZUUeVmwv5rpdx4im5KUYSlWRBfE38DCOTtq";

test("no route imports the native bcrypt addon", () => {
  for (const route of ROUTES) {
    assert.ok(existsSync(route), `${route} should exist`);
    const src = read(route);
    assert.doesNotMatch(
      src,
      /from\s+["']bcrypt["']|require\(\s*["']bcrypt["']\s*\)/,
      `${route} must import "bcryptjs", not the native "bcrypt" addon`,
    );
    assert.match(
      src,
      /from\s+["']bcryptjs["']|require\(\s*["']bcryptjs["']\s*\)/,
      `${route} should import bcryptjs`,
    );
  }
});

test("package.json depends on bcryptjs and no longer on native bcrypt", () => {
  const pkg = JSON.parse(read("package.json"));
  const all = { ...pkg.dependencies, ...pkg.devDependencies };
  assert.ok(all.bcryptjs, "bcryptjs must be a dependency");
  assert.equal(
    all.bcrypt,
    undefined,
    "native bcrypt must not be reintroduced — the routes rely on the pure-JS bcryptjs",
  );
});

test("bcryptjs verifies hashes produced by the reference bcrypt implementation", () => {
  for (const [plaintext, hash] of REFERENCE_VECTORS) {
    assert.equal(
      bcrypt.compareSync(plaintext, hash),
      true,
      `bcryptjs must verify the reference bcrypt hash for ${JSON.stringify(plaintext)}`,
    );
    assert.equal(
      bcrypt.compareSync(`${plaintext}x`, hash),
      false,
      `bcryptjs must reject a wrong password for ${JSON.stringify(plaintext)}`,
    );
  }
});

test("bcryptjs parses and compares against the deployed $2b$ fixture hash", () => {
  // The fixture is a real cost-10 $2b$ hash. We don't know its plaintext, so
  // the guarantee we can assert is that bcryptjs recognises the format and
  // returns a boolean — a throw or undefined here would break login.
  assert.equal(
    bcrypt.getRounds(FIXTURE_HASH),
    10,
    "bcryptjs must parse the cost factor out of an existing $2b$ hash",
  );
  assert.match(
    bcrypt.getSalt(FIXTURE_HASH),
    /^\$2b\$10\$/,
    "bcryptjs must parse the salt out of an existing $2b$ hash",
  );
  assert.equal(
    bcrypt.compareSync("definitely-not-the-password", FIXTURE_HASH),
    false,
    "comparing a wrong password against an existing $2b$ hash must return false, not throw",
  );
});

test("bcryptjs keeps producing $2b$ hashes so the routes' prefix gate still passes", () => {
  // delete-account/route.js gates bcrypt.compare behind a /^\$2[aby]\$/
  // prefix check. If bcryptjs ever changed its output format, new hashes
  // would be written but never verifiable.
  const hash = bcrypt.hashSync("grynd-phase-4", 12);
  assert.match(hash, /^\$2[aby]\$/, "bcryptjs hashes must keep a bcrypt prefix");
  assert.equal(bcrypt.compareSync("grynd-phase-4", hash), true);
  assert.equal(bcrypt.compareSync("wrong", hash), false);
});
