ALTER TABLE users
  ADD COLUMN IF NOT EXISTS referral_code VARCHAR(30) UNIQUE,
  ADD COLUMN IF NOT EXISTS referred_by_id INTEGER,
  ADD COLUMN IF NOT EXISTS referral_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS referral_earnings NUMERIC(10,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_wagered NUMERIC(14,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1;

ALTER TABLE users
  ADD CONSTRAINT users_referred_by_id_fkey
  FOREIGN KEY (referred_by_id) REFERENCES users(id)
  ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS user_stats (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  total_bets INTEGER NOT NULL DEFAULT 0,
  wins INTEGER NOT NULL DEFAULT 0,
  losses INTEGER NOT NULL DEFAULT 0,
  win_rate NUMERIC(5,2) NOT NULL DEFAULT 0,
  total_wagered NUMERIC(14,2) NOT NULL DEFAULT 0,
  total_won NUMERIC(14,2) NOT NULL DEFAULT 0,
  biggest_win NUMERIC(14,2) NOT NULL DEFAULT 0,
  favorite_game VARCHAR(100) NOT NULL DEFAULT 'N/A',
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS users_referral_code_idx ON users(referral_code);
