-- ── 0132: Daily & weekly quests ──
--
-- Per-player, per-period quest rows generated by the hybrid quest engine
-- (src/lib/quests.js). Each row is one quest slot for one period
-- ('daily' | 'weekly') keyed by period_key (UTC date for daily, ISO week
-- for weekly). Progress is incremented by applyLeaderboardCounters as
-- games settle; a claimed flag makes reward credit idempotent.

CREATE TABLE IF NOT EXISTS user_quests (
  id BIGSERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  period_type VARCHAR(10) NOT NULL,       -- 'daily' | 'weekly'
  period_key VARCHAR(12) NOT NULL,        -- 'YYYY-MM-DD' | ISO week 'YYYY-Www'
  slot INTEGER NOT NULL,                  -- 0-based slot within the period
  quest_type VARCHAR(20) NOT NULL,        -- 'play' | 'win' | 'wager' | 'multiplier' | 'streak' | 'diversify' | 'pvp'
  game_key VARCHAR(30),                   -- specific game, or NULL = any game
  target NUMERIC NOT NULL,                -- count or token amount
  reward INTEGER NOT NULL,                -- tokens
  progress NUMERIC NOT NULL DEFAULT 0,
  claimed BOOLEAN NOT NULL DEFAULT FALSE,
  -- Extra state per quest type, e.g. {"wonGames":["chess","roulette"]}
  -- for the 'diversify' quest (distinct games won).
  meta JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, period_type, period_key, slot)
);

CREATE INDEX IF NOT EXISTS idx_user_quests_user_period
  ON user_quests (user_id, period_type, period_key);
