import { NextResponse } from "next/server";
import { logError } from "../../../../lib/logError";

export async function GET() {
  try {
    await logError({
      errorType: "test_error",
      errorMessage: "This is a test error generated by the Grynd PM system.",
      endpoint: "/api/pm/test-error",
      game: "system",
      metadata: {
        source: "pm_test",
      },
    });

    return NextResponse.json({
      success: true,
      message: "Test error logged",
    });
  } catch (error) {
    console.error("Test error logging failed:", error);

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : String(error),
      },
      { status: 500 }
    );
  }
}
