import './globals.css';
import { Providers } from './providers';
import ClerkSafeChatWidget from '../components/ClerkSafeChatWidget';
import DisableInspect from '../components/DisableInspect';
import CsrfFetchGuard from '../components/CsrfFetchGuard';

export const dynamic = 'force-dynamic';

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className="antialiased transition-colors duration-300 bg-[#030817] text-[#d8fbff]">
        <Providers>
          <CsrfFetchGuard />
          <DisableInspect />
          {children}
          <ClerkSafeChatWidget />
        </Providers>
      </body>
    </html>
  );
}
