"use client";

import NavigationBar from "../../components/navigation-bar";
import Footer from "../../components/Footer";
import InteractiveCasinoBg from "../../components/InteractiveCasinoBg";
import { motion } from "framer-motion";
import Link from "next/link";

const sections = [
  {
    title: "Information We Collect",
    content: [
      "We collect only the information needed to run the platform. Everything below is collected directly from you, generated by your use of the platform, or received from the services we integrate with (such as Clerk for sign-in).",
      "Account & identity: your name, email address, username/display name, and Clerk user ID when you create an account; your date of birth, used for age verification (we are an 18+ platform); an optional profile picture if you upload one; and, where applicable, a hashed password for your GRYND account.",
      "Gameplay & activity: your token balance, wagers, wins, losses, game history, streaks, level, XP, titles, biggest win, referral code and referral earnings, login-reward progress, friends, and online/presence status. This is stored to power rankings, leaderboards, and your profile.",
      "Content you submit: chat messages (in global and game rooms), product reviews (rating, title, body, and the game reviewed), contact-form messages (your name, email, and message), and player reports about other users (the reason and any details you provide).",
      "Communications: we keep records of emails we send you (welcome, inactivity/reactivation, and marketing messages) so we can avoid duplicates and manage preferences.",
      "Technical & security data: your IP address (used for rate limiting and security auditing), browser and device information (received from our analytics and error-monitoring providers), and the cookies and local/session storage described below.",
    ],
  },
  {
    title: "How We Use Your Information",
    content: [
      "We use your information to provide, maintain, and improve our services. This includes processing wagers and payouts, calculating rankings and leaderboards, displaying your profile and game history, running the chat and review features, sending account and marketing emails, detecting fraudulent or abusive behavior, and complying with legal obligations.",
      "Public information: your display name, profile picture, level, titles, streaks, and gameplay statistics are shown publicly on leaderboards, rankings, profiles, the Top Wins feed, and (for approved reviews) the reviews page. Your email address and date of birth are never displayed publicly.",
      "We do not sell your personal information. We do show advertising on our browsing pages, served by Google AdSense \u2014 see \u201cAdvertising\u201d below for exactly where it appears and how you control it.",
    ],
  },
  {
    title: "Age Verification & Compliance",
    content: [
      "GRYND is a skill-based gaming platform for adults. We are required to verify that all users are at least 18 years old, and your date of birth is collected and stored for this purpose. Users who do not pass age verification are denied access to the platform.",
      "The platform does not involve real-money wagering. Tokens are virtual credits with no cash value, as described in our Terms of Service.",
    ],
  },
  {
    title: "Analytics & Diagnostics",
    content: [
      "We use PostHog for product analytics (page views, game events such as game started/ended, and signup-funnel events) and Sentry for error and crash reporting. Both providers receive standard browser/device information, and PostHog receives your user ID, name, and email address so events can be tied to a profile.",
      "These analytics and diagnostics are gated behind our cookie-consent banner (required by Quebec's Law 25). If you decline or withdraw consent, client-side capture is disabled. You can change your choice at any time from the consent banner.",
    ],
  },
  {
    title: "Advertising",
    content: [
      "We keep GRYND free to play in part with advertising served by Google AdSense. Ads appear only on browsing pages \u2014 the home page, the games hub, the leaderboard, the battlepass and the game lobbies. They never appear on a live match page, so a game in progress is never interrupted by advertising.",
      "Google and its advertising partners may set cookies or read device identifiers in order to serve and measure ads and to limit how often you see the same ad. Where your consent is required, ads are non-personalised until you consent, and ad click identifiers are redacted from ad requests.",
      "Visitors in the European Economic Area, the United Kingdom and Switzerland are shown a consent message from Google's certified consent management platform, which records your choices and lets you refuse as easily as you accept; that choice is also passed to our advertising partners as an industry-standard consent signal. Visitors elsewhere are shown our own cookie banner.",
      "You can change or withdraw your advertising consent at any time with the \u201cManage cookies\u201d link in the footer of every page. We do not sell your personal information.",
    ],
  },
  {
    title: "Support & Live Chat",
    content: [
      "Our support chat is provided by Tawk.to. When you use the live chat widget, Tawk.to processes your chat messages and contact details under its own privacy policy, as a service provider to us. Chat messages you send on the platform (global and game rooms) are stored by us, are visible to other players, and may be moderated.",
    ],
  },
  {
    title: "Email Communications",
    content: [
      "We send transactional emails (account confirmations and service notices) and, where permitted, marketing and reactivation emails (for example, a welcome email when you sign up, or an inactivity email after a long absence). Marketing emails are sent through Resend and are logged internally. You can opt out of marketing emails at any time by contacting us; transactional emails are required for the service to function.",
    ],
  },
  {
    title: "Data Sharing & Third Parties",
    content: [
      "We share personal data only with the service providers we use to operate the platform, who process it on our behalf under contractual obligations: Clerk (authentication), Neon and Vercel Postgres (database hosting), Vercel (hosting), Upstash (caching), Supabase (supporting services), PostHog (analytics), Sentry (error monitoring), Resend (email delivery), Tawk.to (support chat), and Google (advertising, through AdSense).",
      "Advertising is served through Google AdSense, which processes ad data as an independent controller under its own privacy policy rather than as our service provider; the consent signals described under \u201cAdvertising\u201d are how your choices reach it.",
      "If token purchases are enabled, payment processing is handled by a third-party payment processor; we do not store your card or other payment instrument details.",
      "We may also disclose information where required by law, to enforce our Terms, or to protect the rights, property, or safety of our users or the public.",
    ],
  },
  {
    title: "Data Retention",
    content: [
      "We retain your personal information for as long as your account is active or as needed to provide our services and meet legal obligations.",
      "Finished PvP match records are automatically deleted 45 days after they end (a routine storage-retention sweep). Solo game history that powers your bet-history page is kept while your account is active.",
      "If you delete your account, we erase your personal data: your account, game history, chat messages, reviews, and content you filed are deleted; reports filed against you are kept but anonymized (your identity is removed); and security/compliance audit logs are retained as required by law. This is performed immediately on request — no 30-day waiting period. Backup copies may persist for a limited period before being overwritten.",
    ],
  },
  {
    title: "Your Rights",
    content: [
      "Depending on your jurisdiction (including Quebec's Act respecting the protection of personal information in the private sector — Law 25 — and, where applicable, the GDPR), you have the right to access, correct, or delete your personal data; to request a copy; to restrict or object to certain processing; and to withdraw any consent you gave.",
      "You can access and correct most of your data in your account settings, and you can delete your account at any time from your profile. For anything else, contact us through our contact page — we will respond within 30 days. If you are in Quebec, you may also file a complaint with the Commission d'accès à l'information (CAI).",
    ],
  },
  {
    title: "Cookies & Local Storage",
    content: [
      "GRYND uses strictly necessary cookies and similar technologies to operate and secure the platform: authentication and session cookies (Clerk), a short-lived CSRF-protection cookie, and — for administrators only — a 24-hour security cookie used for the admin second-factor check. These are essential; without them you cannot sign in or use core features.",
      "We also use browser storage (localStorage and sessionStorage) for preferences such as your theme, language, cookie-consent choice, onboarding-tour progress, and short-lived caches of your level and status, as well as a temporary game-session identifier used by some games.",
      "Where analytics, diagnostics or advertising involve non-essential technologies (PostHog, Sentry, Google AdSense), we obtain your consent before enabling them \u2014 see \u201cAnalytics & Diagnostics\u201d and \u201cAdvertising\u201d above. You can change or withdraw that choice at any time with the \u201cManage cookies\u201d link in the footer. You can also manage or delete cookies and storage through your browser settings; disabling essential cookies may prevent you from signing in or using the platform.",
    ],
  },
  {
    title: "Data Security",
    content: [
      "We protect your data with the measures described in our Security Policy, including encryption in transit, rate limiting, CSRF protection, audit logging, and multi-factor authentication for administrative access. No method of transmission or storage is completely secure, and we cannot guarantee absolute security.",
    ],
  },
  {
    title: "Children",
    content: [
      "GRYND is intended for adults aged 18 and over only. We do not knowingly collect personal information from children. If you believe a minor has provided us with personal information, please contact us so we can delete it.",
    ],
  },
  {
    title: "International Data Transfers",
    content: [
      "Our service providers are located in Canada, the United States, and other countries. Where personal information is transferred across borders, we rely on appropriate safeguards (such as standard contractual clauses) and applicable legal requirements.",
    ],
  },
  {
    title: "Changes to This Policy",
    content:
      "We may update this Privacy Policy from time to time to reflect changes in our practices or legal requirements. We will notify you of material changes via email or through a notice on our platform. Your continued use of GRYND after such changes constitutes your acceptance of the updated policy.",
  },
  {
    title: "Governing Law & Disputes",
    content:
      "This Privacy Policy and any dispute arising out of or relating to it, or to our collection, use, and protection of your personal information, shall be governed by and construed in accordance with the laws of the Province of Quebec and the federal laws of Canada applicable therein, without regard to conflict-of-laws principles. Any dispute, claim, or controversy arising out of or relating to this Privacy Policy shall first be resolved through good-faith negotiations between the parties. If the dispute is not resolved within thirty (30) days of the first notice, it shall be resolved by binding arbitration conducted in the Province of Quebec, Canada, under the applicable arbitration rules in effect at that time, and judgment on the arbitral award may be entered in any court of competent jurisdiction. You agree to submit to the personal jurisdiction of the courts of the Province of Quebec for any matters not subject to arbitration and for the enforcement of any arbitration award.",
  },
];

export default function PrivacyPolicyPage() {
  return (
    <div className="relative min-h-screen">
      <InteractiveCasinoBg variant="subtle" />

      <NavigationBar currentPath="/" />

      <div className="mx-auto max-w-4xl px-4 py-16">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="mb-4 text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-[#00e5ff] to-[#f5ff3b]">
            Privacy Policy
          </h1>
          <p className="mb-8 text-lg text-[#9dd8ff]">
            Last updated: September 23, 2026
          </p>

          <div className="mb-8 rounded-lg border border-[#00e5ff]/20 bg-[#040d24]/80 p-6 backdrop-blur-sm">
            <p className="leading-relaxed text-[#c9f7ff]">
              Your privacy matters to us. This Privacy Policy explains how
              GRYND collects, uses, stores, and protects your personal
              information when you use our platform. By using GRYND, you
              consent to the practices described in this policy.
            </p>
          </div>
        </motion.div>

        <div className="space-y-6">
          {sections.map((section, index) => (
            <motion.div
              key={section.title}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.4, delay: index * 0.05 }}
              className="rounded-lg border border-[#00e5ff]/15 bg-[#040d24]/60 p-6 backdrop-blur-sm transition-all hover:border-[#00e5ff]/30 hover:shadow-[0_0_15px_rgba(0,229,255,0.1)]"
            >
              <h2 className="mb-3 text-xl font-bold text-[#00e5ff]">
                {section.title}
              </h2>
              {Array.isArray(section.content) ? (
                <div className="space-y-2">
                  {section.content.map((paragraph, i) => (
                    <p
                      key={i}
                      className="leading-relaxed text-[#c9f7ff]/90"
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>
              ) : (
                <p className="leading-relaxed text-[#c9f7ff]/90">
                  {section.content}
                </p>
              )}
            </motion.div>
          ))}
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.6 }}
          className="mt-10 rounded-lg border border-[#f5ff3b]/20 bg-[#f5ff3b]/5 p-6 text-center"
        >
          <p className="text-sm text-[#c9f7ff]/70">
            For privacy-related inquiries,{" "}
            <Link
              href="/contact"
              className="text-[#f5ff3b] underline decoration-[#f5ff3b]/40 underline-offset-4 hover:text-[#f5ff3b]/80 transition-colors"
            >
              contact us
            </Link>
            .
          </p>
        </motion.div>
      </div>

      <Footer />
    </div>
  );
}
