#!/usr/bin/env node
/**
 * GRYND database backup — dependency-free logical dump.
 *
 * Writes a single, self-contained SQL file that restores the schema AND
 * data of a Postgres database. No pg_dump / psql / Docker required — it
 * uses the `pg` driver already in the project.
 *
 * The output is a plain-SQL file with:
 *   1. header + redacted source info
 *   2. schema DDL   — enums, sequences, tables, constraints, indexes
 *   3. data         — INSERTs in foreign-key order with literal escaping
 *
 * Usage:
 *   DATABASE_URL="postgresql://..." node scripts/db-backup.mjs
 *   # writes ./backups/grynd-<date>.sql  (or use -o to pick a path)
 *
 * Safe defaults: reads are fully read-only (no writes, no locks), and
 * the dump is written to a file. `--stdout` prints to stdout instead.
 */

import fs from "node:fs";
import path from "node:path";
import pg from "pg";
import { qIdent, qLiteral, orderByDependencies } from "./db-backup-lib.mjs";

const { Client } = pg;

const DEFAULT_BACKUP_DIR = "backups";
const dateStamp = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

const url =
  process.env.DATABASE_URL || process.env.POSTGRES_URL || "";
if (!url) {
  console.error(
    "DATABASE_URL (or POSTGRES_URL) is not set — point it at the database to back up.",
  );
  process.exit(1);
}

// --CLI parsing -------------------------------------------------------
let outPath = process.argv.find((a) => a.startsWith("-o="))?.slice(3);
const toStdout = process.argv.includes("--stdout");
const verbose = process.argv.includes("--verbose");

function log(...args) {
  if (verbose) console.error(...args);
}

function makeClient(connectionString) {
  let host = "";
  try {
    host = new URL(connectionString).hostname || "";
  } catch {}
  const isLocal = /localhost|127\.0\.0\.1|::1/.test(host);
  // Strip sslmode — pg merges it over the explicit `ssl` option and
  // re-enables cert verification, which breaks Supabase's pooler.
  const sanitized = connectionString.replace(
    /([?&])sslmode=[^&]*(&|$)/g,
    (_m, prefix, suffix) => (suffix === "&" ? prefix : ""),
  );
  return new Client({
    connectionString: sanitized,
    ssl: isLocal ? undefined : { rejectUnauthorized: false },
  });
}

const client = makeClient(url);

// --Schema helpers (mirror scripts/dump-schema.mjs) -------------------
async function dumpEnums(sqlArr) {
  const { rows } = await client.query(
    `SELECT t.typname, e.enumlabel
     FROM pg_type t
     JOIN pg_enum e ON e.enumtypid = t.oid
     WHERE t.typtype = 'e' AND t.typnamespace = 'public'::regnamespace
     ORDER BY t.typname, e.enumsortorder`,
  );
  const byName = new Map();
  for (const r of rows) {
    if (!byName.has(r.typname)) byName.set(r.typname, []);
    byName.get(r.typname).push(r.enumlabel);
  }
  for (const [name, labels] of byName) {
    sqlArr.push(
      `CREATE TYPE ${qIdent(name)} AS ENUM (${labels
        .map((l) => `'${l.replace(/'/g, "''")}'`)
        .join(", ")});`,
    );
  }
  if (byName.size) sqlArr.push("");
}

async function dumpSequences(sqlArr) {
  const { rows } = await client.query(
    `SELECT sequencename FROM pg_sequences WHERE schemaname = 'public' ORDER BY sequencename`,
  );
  for (const r of rows) {
    sqlArr.push(`CREATE SEQUENCE IF NOT EXISTS ${qIdent(r.sequencename)};`);
  }
  if (rows.length) sqlArr.push("");
}

async function dumpTables(sqlArr) {
  const { rows } = await client.query(
    `SELECT tablename FROM pg_tables
     WHERE schemaname = 'public' AND tablename <> '__drizzle_migrations'
     ORDER BY tablename`,
  );
  for (const r of rows) {
    const table = r.tablename;
    const cols = await client.query(
      `SELECT a.attname,
              pg_catalog.format_type(a.atttypid, a.atttypmod) AS ddl_type,
              a.attnotnull, a.attidentity, a.attgenerated,
              COALESCE(pg_get_expr(ad.adbin, ad.adrelid), '') AS def_expr
       FROM pg_attribute a
       JOIN pg_class c ON c.oid = a.attrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
       LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
       WHERE n.nspname = 'public' AND c.relname = $1 AND a.attnum > 0 AND NOT a.attisdropped
       ORDER BY a.attnum`,
      [table],
    );
    const colDefs = [];
    for (const c of cols.rows) {
      let def = `  ${qIdent(c.attname)} ${c.ddl_type}`;
      if (c.attidentity === "a") def += " GENERATED ALWAYS AS IDENTITY";
      else if (c.attidentity === "d") def += " GENERATED BY DEFAULT AS IDENTITY";
      if (c.attgenerated === "s") def += ` GENERATED ALWAYS AS (${c.def_expr}) STORED`;
      else if (!c.attidentity && c.def_expr) def += ` DEFAULT ${c.def_expr}`;
      if (c.attnotnull) def += " NOT NULL";
      colDefs.push(def);
    }
    sqlArr.push(
      `CREATE TABLE IF NOT EXISTS ${qIdent(table)} (\n${colDefs.join(",\n")}\n);`,
    );
  }
  if (rows.length) sqlArr.push("");
}

async function dumpConstraints(sqlArr) {
  const { rows: tables } = await client.query(
    `SELECT tablename FROM pg_tables
     WHERE schemaname = 'public' AND tablename <> '__drizzle_migrations'
     ORDER BY tablename`,
  );
  const tableNames = tables.rows.map((r) => r.tablename);

  // Phase A: PK / UNIQUE / CHECK for ALL tables (parent constraints first).
  for (const table of tableNames) {
    const cons = await client.query(
      `SELECT con.conname, pg_get_constraintdef(con.oid) AS def, con.contype
       FROM pg_constraint con
       JOIN pg_class c ON c.oid = con.conrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public' AND c.relname = $1 AND con.contype IN ('p','u','c')
       ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 ELSE 2 END`,
      [table],
    );
    for (const con of cons.rows) {
      sqlArr.push(
        `ALTER TABLE ONLY ${qIdent(table)} ADD CONSTRAINT ${qIdent(con.conname)} ${con.def};`,
      );
    }
  }
  sqlArr.push("");

  // Phase B: FKs (now that every referenced table has its PK/UNIQUE).
  for (const table of tableNames) {
    const fks = await client.query(
      `SELECT con.conname, pg_get_constraintdef(con.oid) AS def
       FROM pg_constraint con
       JOIN pg_class c ON c.oid = con.conrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public' AND c.relname = $1 AND con.contype = 'f'
       ORDER BY con.conname`,
      [table],
    );
    for (const con of fks.rows) {
      sqlArr.push(
        `ALTER TABLE ONLY ${qIdent(table)} ADD CONSTRAINT ${qIdent(con.conname)} ${con.def};`,
      );
    }
  }
  sqlArr.push("");
}

async function dumpIndexes(sqlArr) {
  const { rows: tables } = await client.query(
    `SELECT tablename FROM pg_tables
     WHERE schemaname = 'public' AND tablename <> '__drizzle_migrations'
     ORDER BY tablename`,
  );
  for (const r of tables.rows) {
    const table = r.tablename;
    const indexes = await client.query(
      `SELECT pg_get_indexdef(i.oid) AS def
       FROM pg_index idx
       JOIN pg_class i ON i.oid = idx.indexrelid
       JOIN pg_class c ON c.oid = idx.indrelid
       JOIN pg_namespace n ON n.oid = c.relnamespace
       WHERE n.nspname = 'public' AND c.relname = $1
         AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = idx.indexrelid)
       ORDER BY i.relname`,
      [table],
    );
    for (const ix of indexes.rows) {
      sqlArr.push(`${ix.def.replace(/;\s*$/, "")};`);
    }
  }
  sqlArr.push("");
}

// --Data helpers ------------------------------------------------------
async function listDataTables() {
  const { rows } = await client.query(
    `SELECT tablename FROM pg_tables
     WHERE schemaname = 'public' AND tablename <> '__drizzle_migrations'
     ORDER BY tablename`,
  );
  return rows.map((r) => r.tablename);
}

async function tableColumns(table) {
  const { rows } = await client.query(
    `SELECT column_name, data_type, column_default, is_identity, is_generated
     FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = $1
     ORDER BY ordinal_position`,
    [table],
  );
  return rows;
}

async function dumpTableData(sqlArr, table) {
  const cols = await tableColumns(table);
  if (cols.length === 0) return 0;

  // Skip identity / generated columns ONLY where the server can compute
  // them (GENERATED ALWAYS). Identity columns are real user data (serial
  // ids) — we keep them and let sequence restoration realign values.
  const insertCols = cols.filter((c) => c.is_generated !== "ALWAYS");
  if (insertCols.length === 0) return 0;

  const names = insertCols.map((c) => c.column_name);
  const quoted = names.map(qIdent);

  // Count first so we can report progress and skip empties.
  const count = await client.query(`SELECT COUNT(*)::int AS n FROM ${qIdent(table)}`);
  const n = count.rows[0].n;
  if (n === 0) {
    log(`  ${table}: 0 rows (skipped)`);
    return 0;
  }

  const colList = quoted.join(", ");
  const BATCH = 500;
  let written = 0;
  sqlArr.push(`-- ${table} (${n} rows)`);
  let first = true;
  let lastPk = null;

  // Single-column PK lets us page; otherwise read everything at once.
  const pk = await client.query(
    `SELECT a.attname FROM pg_index i
     JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
     WHERE i.indrelid = ${qIdent(table)}::regclass AND i.indisprimary`,
  );
  const pkCol = pk.rows.length === 1 ? pk.rows[0].attname : null;

  while (true) {
    const where = lastPk != null && pkCol ? ` WHERE ${qIdent(pkCol)} > ${lastPk}` : "";
    const q = `SELECT ${colList} FROM ${qIdent(table)}${where} ORDER BY ${
      pkCol ? qIdent(pkCol) : "1"
    } LIMIT ${BATCH}`;
    const { rows } = await client.query(q);
    if (!rows.length) break;
    if (pkCol != null) lastPk = rows[rows.length - 1][pkCol];
    for (const row of rows) {
      const vals = names.map((c) => qLiteral(row[c]));
      if (first) {
        sqlArr.push(
          `INSERT INTO ${qIdent(table)} (${colList}) VALUES\n  (${vals.join(", ")})`,
        );
        first = false;
      } else {
        sqlArr.push(`  ,(${vals.join(", ")})`);
      }
      written += 1;
    }
    if (rows.length < BATCH) break;
  }
  sqlArr.push(";");
  sqlArr.push("");
  log(`  ${table}: ${written} rows`);
  return written;
}

async function dumpSequencesData(sqlArr) {
  // Realign every serial/identity sequence after a restore so inserts keep
  // working. Match columns by their nextval() default (NOT
  // pg_get_serial_sequence — that dependency can be missing after a schema
  // restore, exactly what broke the Neon→Supabase migration). Identical to
  // fixSequences() in scripts/migrate-data.mjs.
  const { rows: tables } = await client.query(
    `SELECT tablename FROM pg_tables
     WHERE schemaname = 'public' AND tablename <> '__drizzle_migrations'
     ORDER BY tablename`,
  );
  let count = 0;
  for (const r of tables.rows) {
    const table = r.tablename;
    const cols = await client.query(
      `SELECT column_name, column_default
       FROM information_schema.columns
       WHERE table_schema = 'public' AND table_name = $1
         AND column_default LIKE 'nextval(%'`,
      [table],
    );
    for (const col of cols.rows) {
      const m = col.column_default.match(/nextval\('([^']+)'::regclass\)/);
      if (!m) continue;
      sqlArr.push(
        `SELECT setval(${qLiteral(m[1])}, COALESCE((SELECT MAX(${qIdent(
          col.column_name,
        )}) FROM ${qIdent(table)}), 1), true);`,
      );
      count += 1;
    }
  }
  if (count) sqlArr.push("");
}

// --Main----------------------------------------------------------------
try {
  await client.connect();
  log(`Connected to ${new URL(url).hostname} (${new URL(url).pathname.slice(1)})`);

  const lines = [];
  lines.push("-- GRYND database backup (generated by scripts/db-backup.mjs)");
  lines.push(`-- Generated: ${new Date().toISOString()}`);
  lines.push(`-- Source: ${url.replace(/\/\/[^@/]+@/, "//***@")}`);
  lines.push("--");
  lines.push("-- Restore with: DATABASE_URL=... node scripts/db-restore.mjs <this file>");
  lines.push("--");
  lines.push("BEGIN;");
  lines.push("");

  await dumpEnums(lines);
  await dumpSequences(lines);
  await dumpTables(lines);
  await dumpConstraints(lines);
  await dumpIndexes(lines);

  // Data — in foreign-key order (parents before children).
  const tables = await listDataTables();
  const fkRows = (
    await client.query(
      `SELECT tc.table_name AS child, ccu.table_name AS parent
       FROM information_schema.table_constraints tc
       JOIN information_schema.constraint_column_usage ccu ON tc.constraint_name = ccu.constraint_name
       WHERE tc.constraint_type = 'FOREIGN KEY' AND tc.table_schema = 'public'`,
    )
  ).rows;
  const ordered = orderByDependencies(tables, fkRows);
  log(`Data tables (${ordered.length}): ${ordered.join(", ")}`);
  let dataRows = 0;
  for (const table of ordered) {
    dataRows += await dumpTableData(lines, table);
  }

  // Sequence realignment (after data).
  await dumpSequencesData(lines);

  lines.push("COMMIT;");
  lines.push("");

  const sql = lines.join("\n");

  if (toStdout) {
    process.stdout.write(sql);
    console.error(`Backed up ${tables.length} tables, ${ordered.length} with data (stdout).`);
    await client.end();
    process.exit(0);
  }

  // Default: write to backups/
  outPath ||= path.join(DEFAULT_BACKUP_DIR, `grynd-${dateStamp}.sql`);
  if (!outPath.includes(path.sep) && !outPath.startsWith("backups")) {
    outPath = path.join(DEFAULT_BACKUP_DIR, outPath);
  }
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, sql, "utf8");
  console.log(`Backup written to ${outPath} (${(sql.length / 1024 / 1024).toFixed(2)} MB)`);
  console.log(`Tables: ${tables.length}; data rows: ${dataRows}`);
} catch (err) {
  console.error("Backup failed:", err.message);
  process.exitCode = 1;
} finally {
  await client.end().catch(() => {});
}