#!/usr/bin/env node
/**
 * Dump the full public schema of a Postgres database as DDL, mirroring
 * `pg_dump --schema-only` closely enough to rebuild the schema elsewhere.
 * Used for the Neon → Supabase migration: the live Neon schema is the
 * ground truth (migration SQL files were never the source of truth).
 *
 * Emitted in dependency-safe phases:
 *   1. CREATE TYPE for enums + CREATE SEQUENCE
 *   2. CREATE TABLE for ALL tables (columns, types, defaults, not-null)
 *   3. ALTER TABLE ADD CONSTRAINT for ALL tables (PK, UNIQUE, CHECK, then FK)
 *   4. CREATE INDEX (non-constraint indexes)
 *
 * Usage: SOURCE_URL="postgresql://..." node scripts/dump-schema.mjs > schema.sql
 */
import pg from "pg";

const { Client } = pg;

const url = process.env.SOURCE_URL || process.env.NEON_URL;
if (!url) {
  console.error("Usage: SOURCE_URL=... node scripts/dump-schema.mjs > schema.sql");
  process.exit(1);
}

const client = new Client({
  connectionString: url,
  ssl: { rejectUnauthorized: false },
});
await client.connect();

const out = [];
const push = (s = "") => out.push(s);

// ── Phase 1a: Enums ──────────────────────────────────────────────────
const enums = await client.query(
  `SELECT t.typname, e.enumlabel
   FROM pg_type t
   JOIN pg_enum e ON e.enumtypid = t.oid
   WHERE t.typtype = 'e' AND t.typnamespace = 'public'::regnamespace
   ORDER BY t.typname, e.enumsortorder`,
);
const enumValues = new Map();
for (const r of enums.rows) {
  if (!enumValues.has(r.typname)) enumValues.set(r.typname, []);
  enumValues.get(r.typname).push(r.enumlabel);
}
for (const [name, labels] of enumValues) {
  push(`CREATE TYPE "public"."${name}" AS ENUM (${labels.map((l) => `'${l.replace(/'/g, "''")}'`).join(", ")});`);
}
if (enumValues.size) push("");

// ── Phase 1b: Sequences ──────────────────────────────────────────────
const seqs = await client.query(
  `SELECT sequencename FROM pg_sequences WHERE schemaname = 'public' ORDER BY sequencename`,
);
for (const r of seqs.rows) {
  push(`CREATE SEQUENCE IF NOT EXISTS "public"."${r.sequencename}";`);
}
if (seqs.rows.length) push("");

// ── Phase 2: Tables ──────────────────────────────────────────────────
const tables = await client.query(
  `SELECT tablename FROM pg_tables
   WHERE schemaname = 'public' AND tablename <> '__drizzle_migrations'
   ORDER BY tablename`,
);
const tableNames = tables.rows.map((r) => r.tablename);

const colCache = new Map();
for (const table of tableNames) {
  const cols = await client.query(
    `SELECT a.attname,
            pg_catalog.format_type(a.atttypid, a.atttypmod) AS ddl_type,
            a.attnotnull,
            a.attidentity,
            a.attgenerated,
            COALESCE(pg_get_expr(ad.adbin, ad.adrelid), '') AS def_expr
     FROM pg_attribute a
     JOIN pg_class c ON c.oid = a.attrelid
     JOIN pg_namespace n ON n.oid = c.relnamespace
     LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
     WHERE n.nspname = 'public' AND c.relname = $1 AND a.attnum > 0 AND NOT a.attisdropped
     ORDER BY a.attnum`,
    [table],
  );
  colCache.set(table, cols.rows);

  const colDefs = [];
  for (const c of cols.rows) {
    let def = `  "${c.attname}" ${c.ddl_type}`;
    if (c.attidentity === "a") def += " GENERATED ALWAYS AS IDENTITY";
    else if (c.attidentity === "d") def += " GENERATED BY DEFAULT AS IDENTITY";
    if (c.attgenerated === "s") {
      def += ` GENERATED ALWAYS AS (${c.def_expr}) STORED`;
    } else if (!c.attidentity && c.def_expr) {
      def += ` DEFAULT ${c.def_expr}`;
    }
    if (c.attnotnull) def += " NOT NULL";
    colDefs.push(def);
  }
  push(`CREATE TABLE IF NOT EXISTS "public"."${table}" (\n${colDefs.join(",\n")}\n);`);
}
push("");

// ── Phase 3: Constraints — sub-phase A: PK/UNIQUE/CHECK for ALL tables ─
for (const table of tableNames) {
  const cons = await client.query(
    `SELECT con.conname, pg_get_constraintdef(con.oid) AS def, con.contype
     FROM pg_constraint con
     JOIN pg_class c ON c.oid = con.conrelid
     JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relname = $1 AND con.contype IN ('p','u','c')
     ORDER BY CASE con.contype WHEN 'p' THEN 0 WHEN 'u' THEN 1 ELSE 2 END`,
    [table],
  );
  for (const con of cons.rows) {
    push(`ALTER TABLE ONLY "public"."${table}" ADD CONSTRAINT "${con.conname}" ${con.def};`);
  }
}
push("");

// ── Phase 3b: Constraints — sub-phase B: FKs for ALL tables (now that
// every referenced table has its PK/UNIQUE constraints) ───────────────
for (const table of tableNames) {
  const fks = await client.query(
    `SELECT con.conname, pg_get_constraintdef(con.oid) AS def
     FROM pg_constraint con
     JOIN pg_class c ON c.oid = con.conrelid
     JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relname = $1 AND con.contype = 'f'
     ORDER BY con.conname`,
    [table],
  );
  for (const con of fks.rows) {
    push(`ALTER TABLE ONLY "public"."${table}" ADD CONSTRAINT "${con.conname}" ${con.def};`);
  }
}
push("");

// ── Phase 4: Indexes ─────────────────────────────────────────────────
for (const table of tableNames) {
  const indexes = await client.query(
    `SELECT pg_get_indexdef(i.oid) AS def
     FROM pg_index idx
     JOIN pg_class i ON i.oid = idx.indexrelid
     JOIN pg_class c ON c.oid = idx.indrelid
     JOIN pg_namespace n ON n.oid = c.relnamespace
     WHERE n.nspname = 'public' AND c.relname = $1
       AND NOT EXISTS (SELECT 1 FROM pg_constraint con WHERE con.conindid = idx.indexrelid)
     ORDER BY i.relname`,
    [table],
  );
  for (const ix of indexes.rows) {
    push(`${ix.def.replace(/;\s*$/, "")};`);
  }
}

console.log(out.join("\n"));
await client.end();
console.error(`Dumped ${tableNames.length} tables, ${enumValues.size} enums, ${seqs.rows.length} sequences.`);
