/**
 * Crash Arena — Round State Machine (Crash Poker)
 *
 * Phases:
 *   waiting   — players opt in (PLAY) or opt out (SIT OUT)
 *   running   — the hand is live: blinds/ante posted, betting checkpoints
 *               open at 1.25x and every +0.25x after; players fold / call /
 *               raise; the crash curve climbs underneath
 *   crashed   — multiplier hit crash point (or the hand folded out), the
 *               hand is over
 *   settling  — winner determined (fold-order / pot rules), pot distributed
 *
 * This is the CLIENT-SIDE MIRROR of the server-authoritative hand state.
 * The server (API routes + src/lib/crash-poker) is the source of truth for
 * money; this module only renders and drives the betting UI. Every betting
 * action is validated again on the server.
 *
 * Server-authoritative design (unchanged):
 *   • crashPoint is NEVER generated by the client, and since Crash Poker
 *     hides it until the crash, the client mirror carries `crashPoint: null`
 *     for the whole hand — the crash multiplier arrives only with the crash
 *     event (server broadcast / settled-round reveal).
 *   • seedHash is published before the hand; seed is revealed after for verification.
 *   • the winner & payout are determined server-side via the pure Crash Poker
 *     rules engine (resolveHand) — never hardcoded here.
 *
 * Side pots: the local crash-path settlement mirrors the server's tier
 * accounting (computePots) so the result modal can show the main/side pot
 * split and side-pot refunds — the server's numbers always win when
 * serverResults are provided.
 */

import { computePots } from "../crash-poker/roundSystem";

// ── Factory ───────────────────────────────────────────────────────────────

/** Create initial round state from player list. */
export function createRoundState(players = [], roundNumber = 1) {
  return {
    phase: "waiting",
    roundNumber,
    pot: 0,
    carryOver: 0,
    // Crash Poker: the crash point is server-only until the crash, so this
    // stays null during the hand; crashMultiplier is set from the crash
    // event (server broadcast / settled reveal).
    crashPoint: null,
    crashMultiplier: null,   // actual multiplier where crash occurred
    seedHash: null,          // published before the hand (commitment)
    seed: null,              // revealed after the hand (for verification)
    startedAt: null,         // server epoch ms — aligns the shared curve
    // Epoch-ms the current flight segment started (hand start, or the
    // moment the last checkpoint closed) — drives the pause-aware curve
    // that stops at every 0.25x betting checkpoint.
    flightResumedAt: null,
    // Server-authoritative wall-clock deadline for the NEXT round start
    // (set when a hand settles) — every client counts down to it so the
    // round never fires before a client's countdown ends.
    nextRoundAt: null,
    // ── Crash Poker hand window ──────────────────────────────────────────
    checkpointIndex: -1,     // 0 = 1.25x, 1 = 1.50x, ... (-1 = none open)
    currentCheckpointMultiplier: null,
    requiredBet: 0,          // total contribution needed to stay in
    bettingOpen: false,      // whether the checkpoint window accepts actions
    smallBlind: null,
    bigBlind: null,
    dealerPosition: null,
    // Stall guard: epoch-ms deadline for the open checkpoint window (the
    // server auto-folds unmatched players who don't act in time).
    windowDeadlineAt: null,
    players: players.map((p) => ({
      ...p,
      isPlaying: !p.isSittingOut,
      // ── Crash Poker hand fields ────────────────────────────────────────
      contributed: 0,        // committed to the pot this hand
      isActive: false,       // still in the hand
      folded: false,
      foldedAtMultiplier: null,
      lastAction: null,
      allIn: false,          // committed whole stack — can no longer act
      actedThisCheckpoint: false, // has acted at the current checkpoint window
      // Legacy solo-crash field kept so existing UI reads don't crash.
      cashoutMultiplier: null,
      busted: false,
    })),
    results: null,
  };
}

// ── Transitions ───────────────────────────────────────────────────────────

/**
 * Start a new Crash Poker hand.
 *
 * @param state      Current round state (must be "waiting")
 * @param wager      Big blind / table wager amount
 * @param crashPoint Server-authoritative crash point. Crash Poker keeps it
 *                   server-only until the crash, so pass null here — the
 *                   mirror stores it (null) and the crash multiplier arrives
 *                   with the crash event instead. Never generated client-side.
 * @param seedHash   SHA-256 hash of the hand seed (published before the hand)
 * @param seed       The hand seed (revealed after the hand for verification)
 * @param hand       Server hand snapshot: { smallBlind, bigBlind, dealerPosition,
 *                   checkpointIndex, requiredBet, bettingOpen, carryOver,
 *                   startedAt, contributions: [{ userId, amount, role }] }
 */
export function startRound(state, wager, crashPoint = null, seedHash = null, seed = null, hand = null) {
  if (state.phase !== "waiting") return state;

  // A crashPoint may be null (Crash Poker hides it until the crash) or a
  // positive number (legacy flows that still reveal it). Anything else is a
  // bug — never accept a client-generated crash point.
  if (crashPoint != null && (!Number.isFinite(crashPoint) || crashPoint < 1)) {
    console.warn("[roundSystem] startRound called with an invalid crashPoint — refusing.");
    return state;
  }

  const contributions = hand?.contributions || [];
  const carryOver = Number(hand?.carryOver ?? 0);

  const players = state.players.map((p) => {
    const isPlaying = p.isPlaying && !p.isSittingOut;
    const c = contributions.find(
      (x) => x.userId != null && p.userId != null && x.userId === p.userId,
    );
    // A player only enters the hand if they have an entry (a late joiner
    // mid-hand stays seated but sits out until the next hand).
    const inHand = Boolean(c) && isPlaying;
    const amount = c ? Number(c.amount) : 0;
    // Folded state for players who folded before this client synced.
    const wasFolded = Boolean(c?.isActive === false);
    return {
      ...p,
      balance: inHand ? Math.max(0, Number(p.balance) - amount) : p.balance,
      contributed: inHand ? amount : 0,
      isActive: inHand && !wasFolded,
      folded: wasFolded,
      foldedAtMultiplier:
        wasFolded && c?.foldedAtMultiplier != null
          ? Number(c.foldedAtMultiplier)
          : null,
      lastAction: inHand
        ? c?.role === "bb"
          ? "bb"
          : c?.role === "sb"
            ? "sb"
            : "ante"
        : null,
      allIn: inHand ? Boolean(c?.allIn) : false,
      // All-in players are committed (no decision owed); everyone else must
      // act at the open checkpoint before it resolves.
      actedThisCheckpoint: inHand ? Boolean(c?.allIn) : false,
      cashoutMultiplier: null,
      busted: false,
    };
  });

  const pot = players.reduce((sum, p) => sum + Number(p.contributed), 0) + carryOver;

  return {
    ...state,
    phase: "running",
    pot,
    carryOver,
    crashPoint,
    crashMultiplier: null,
    seedHash,
    seed,
    startedAt: hand?.startedAt != null ? Number(hand.startedAt) : null,
    // The flight starts at the hand start; it resumes from the checkpoint
    // multiplier each time a betting window closes (server-authoritative).
    flightResumedAt:
      hand?.flightResumedAt != null
        ? Number(hand.flightResumedAt)
        : hand?.startedAt != null
          ? Number(hand.startedAt)
          : null,
    checkpointIndex: hand?.checkpointIndex ?? -1,
    currentCheckpointMultiplier:
      hand?.currentCheckpointMultiplier ??
      (hand?.checkpointIndex != null && hand.checkpointIndex >= 0
        ? (125 + 25 * hand.checkpointIndex) / 100
        : null),
    requiredBet: Number(hand?.requiredBet ?? 0),
    bettingOpen: Boolean(hand?.bettingOpen),
    windowDeadlineAt: hand?.windowDeadlineAt ?? null,
    smallBlind: hand?.smallBlind != null ? Number(hand.smallBlind) : null,
    bigBlind: hand?.bigBlind != null ? Number(hand.bigBlind) : null,
    dealerPosition: hand?.dealerPosition ?? null,
    players,
    results: null,
  };
}

/**
 * Apply a betting action to the local mirror. `action` is one of
 * "fold" | "call" | "raise". Values are taken from the server response when
 * provided (server is authoritative); otherwise derived locally for the
 * optimistic path.
 */
export function applyPlayerAction(state, playerName, action, amount = null, server = null) {
  if (state.phase !== "running") return state;

  const multiplier = state.currentCheckpointMultiplier;
  const players = state.players.map((p) => {
    if (p.name !== playerName || !p.isActive || p.folded) return p;
    if (server && server.contributed != null) {
      // Apply the server-authoritative numbers directly.
      return {
        ...p,
        contributed: Number(server.contributed),
        balance: Math.max(0, Number(p.balance) - (Number(server.contributed) - Number(p.contributed))),
        lastAction: server.action ?? action,
        isActive: action === "fold" ? false : p.isActive,
        folded: action === "fold",
        foldedAtMultiplier: action === "fold" ? multiplier : p.foldedAtMultiplier,
        allIn: Boolean(server.allIn ?? p.allIn),
        actedThisCheckpoint: true,
      };
    }
    // Optimistic local derivation (the server re-validates + caps).
    let next = { ...p, lastAction: action, actedThisCheckpoint: true };
    if (action === "fold") {
      next = {
        ...next,
        isActive: false,
        folded: true,
        foldedAtMultiplier: multiplier,
      };
    } else if (action === "call") {
      const amt = Math.max(0, Number(amount ?? Math.max(0, state.requiredBet - p.contributed)));
      const capped = Math.min(amt, Math.max(0, Number(p.balance)));
      next = {
        ...next,
        contributed: p.contributed + capped,
        balance: Math.max(0, p.balance - capped),
        lastAction: capped > 0 ? "call" : "check",
        // Committed everything they have left.
        allIn: capped > 0 && capped >= Number(p.balance) + Number.EPSILON,
      };
    } else if (action === "raise") {
      const raiseTo = Number(amount);
      const amt = Math.max(0, raiseTo - p.contributed);
      const capped = Math.min(amt, Math.max(0, Number(p.balance)));
      next = {
        ...next,
        contributed: p.contributed + capped,
        balance: Math.max(0, p.balance - capped),
        lastAction: "raise",
        allIn: capped >= Number(p.balance) + Number.EPSILON,
      };
    }
    return next;
  });

  const pot = players.reduce((sum, p) => sum + Number(p.contributed), 0) + Number(state.carryOver);
  const requiredBet = action === "raise" ? Number(amount) : state.requiredBet;
  const active = players.filter((p) => p.isActive && !p.folded);
  // A checkpoint resolves once every active player has acted (all-in
  // players are committed and never block). Matched-but-silent players
  // still block — matching alone doesn't close betting.
  const resolved =
    active.length > 0 &&
    active.every((p) => p.allIn || p.actedThisCheckpoint);
  const bettingOpen = server && typeof server.bettingOpen === "boolean"
    ? server.bettingOpen
    : !resolved;
  const checkpointIndex =
    server && server.checkpointIndex != null ? Number(server.checkpointIndex) : state.checkpointIndex;

  return {
    ...state,
    pot,
    requiredBet: server && server.requiredBet != null ? Number(server.requiredBet) : requiredBet,
    bettingOpen,
    windowDeadlineAt:
      server && server.windowDeadlineAt != null
        ? Number(server.windowDeadlineAt)
        : state.windowDeadlineAt,
    checkpointIndex,
    currentCheckpointMultiplier:
      server && server.currentCheckpointMultiplier != null
        ? Number(server.currentCheckpointMultiplier)
        : state.currentCheckpointMultiplier,
    players,
  };
}

/**
 * Mark the hand as crashed. Records the final multiplier. Every player still
 * active (not folded) busts.
 */
export function crashRound(state, crashMultiplier) {
  if (state.phase !== "running") return state;

  const players = state.players.map((p) => {
    if (p.isActive && !p.folded) {
      return { ...p, busted: true };
    }
    return p;
  });

  return {
    ...state,
    phase: "crashed",
    crashMultiplier,
    players,
  };
}

/**
 * Local fold-order tie-break (mirror of the server's latestSuccessfulFold):
 * among the folded players, the latest fold wins — the one at the highest
 * checkpoint multiplier, breaking same-checkpoint ties by roster order
 * (deterministic; the server's action log is authoritative for exact order).
 *
 * @param {Array} players roundState.players
 * @returns {object|null} the winning folded player
 */
function latestSuccessfulFoldLocal(players) {
  const folds = players.filter((p) => p.folded && p.foldedAtMultiplier != null);
  if (folds.length === 0) return null;
  let best = null;
  for (const p of folds) {
    if (!best) {
      best = p;
      continue;
    }
    if (Number(p.foldedAtMultiplier) !== Number(best.foldedAtMultiplier)) {
      if (Number(p.foldedAtMultiplier) > Number(best.foldedAtMultiplier)) best = p;
      continue;
    }
    if (players.indexOf(p) > players.indexOf(best)) best = p;
  }
  return best;
}

/**
 * Settle the hand — determine winner and distribute pot (local mirror of the
 * server's fold-order rules).
 *
 * Winner = the sole active player left (everyone else folded), or — when the
 * crash catches 2+ active players — the LATEST successful fold before the
 * crash (the fold-order mechanic). The winner takes the whole pot minus the
 * 5% platform fee; folded players keep only their losses; there are no
 * side-pot returns. When nobody folded and 2+ players were active at the
 * crash, nobody wins and the pot carries over.
 *
 * When `serverResults` is provided (a hand that folded out on the server, or
 * a settled round reconciled over the socket) it is used verbatim — the
 * server is authoritative.
 */
export function settleRound(state, serverResults = null) {
  if (state.phase !== "crashed" && state.phase !== "running") return state;

  const active = state.players.filter((p) => p.isActive && !p.folded && !p.busted);
  const folded = state.players.filter((p) => p.folded && p.foldedAtMultiplier != null);

  let results;
  if (serverResults) {
    results = serverResults;
  } else {
    // Local mirror of the server's fold-order settlement. The server is
    // authoritative — this only drives the modal until the authoritative
    // results land.
    const pot = Number(state.pot);
    const pots = computePots(
      { players: state.players.map((p) => ({
        ...p,
        isActive: p.isActive && !p.busted,
      })), carryOver: state.carryOver },
      state.carryOver,
    );
    const winner =
      active.length === 1
        ? active[0]
        : folded.length > 0
          ? latestSuccessfulFoldLocal(state.players)
          : null;
    const foldedPlayers = state.players
      .filter((p) => p.folded && p.name !== winner?.name)
      .map((p) => ({ name: p.name, at: p.foldedAtMultiplier ?? null }));
    const bustedPlayers = state.players.filter((p) => p.busted).map((p) => p.name);
    // A fold-order winner won by folding — their fold checkpoint is the
    // relevant multiplier; a fold-out winner just needs the open checkpoint.
    const wonByFold = Boolean(winner?.folded);
    if (winner) {
      const payoutGross = pot;
      const fee = Math.floor(payoutGross * 0.05);
      results = {
        winner: winner.name,
        winnerCheckpoint: wonByFold
          ? winner.foldedAtMultiplier
          : state.currentCheckpointMultiplier,
        winnerMultiplier: wonByFold
          ? winner.foldedAtMultiplier
          : state.currentCheckpointMultiplier,
        wonByFold,
        payout: payoutGross - fee,
        fee,
        carryOver: 0,
        potDistributed: payoutGross - fee,
        allCashouts: [],
        returns: [],
        pots,
        foldedPlayers,
        bustedPlayers,
        activeAtCrash: state.players.filter((p) => p.busted).map((p) => p.userId),
      };
    } else {
      results = {
        winner: null,
        winnerCheckpoint: null,
        winnerMultiplier: null,
        wonByFold: false,
        payout: 0,
        fee: 0,
        carryOver: pot,
        potDistributed: 0,
        allCashouts: [],
        returns: [],
        pots,
        foldedPlayers,
        bustedPlayers,
        activeAtCrash: state.players.filter((p) => p.busted).map((p) => p.userId),
      };
    }
  }

  // Apply the winner's payout to local balances so the sidebar matches the
  // modal (server numbers when provided), and attach display names to any
  // refunds + fold checkpoints for the result modal. The authoritative
  // folded/busted rosters are filled in here when the caller (e.g. the
  // socket results payload) didn't ship them.
  const nameById = new Map(state.players.map((p) => [p.userId, p.name]));
  const resultsWithNames = results
    ? {
        ...results,
        returns: (results?.returns || []).map((r) => ({
          userId: r.userId,
          amount: Number(r.amount || 0),
          name: r.name ?? nameById.get(r.userId) ?? null,
        })),
        foldedPlayers: Array.isArray(results?.foldedPlayers)
          ? results.foldedPlayers
          : state.players
              .filter((p) => p.folded && p.name !== results?.winner)
              .map((p) => ({ name: p.name, at: p.foldedAtMultiplier ?? null })),
        bustedPlayers: Array.isArray(results?.bustedPlayers)
          ? results.bustedPlayers
          : state.players.filter((p) => p.busted).map((p) => p.name),
      }
    : null;
  const returnByUserId = new Map(
    (resultsWithNames?.returns || []).map((r) => [r.userId, Number(r.amount || 0)]),
  );
  const players = state.players.map((p) => {
    const returnAmt = returnByUserId.get(p.userId) ?? 0;
    const won = resultsWithNames?.winner && p.name === resultsWithNames.winner;
    const credit = (won ? Number(resultsWithNames.payout || 0) : 0) + returnAmt;
    return credit > 0 ? { ...p, balance: Number(p.balance) + credit } : p;
  });

  return {
    ...state,
    phase: "settling",
    results: resultsWithNames,
    players,
    carryOver: resultsWithNames?.carryOver ?? 0,
  };
}

/**
 * Move to the next hand — reset hand state, increment round number.
 * Seed/seedHash from the previous hand are cleared.
 */
export function nextRound(state) {
  if (state.phase !== "settling") return state;

  return {
    ...state,
    phase: "waiting",
    roundNumber: state.roundNumber + 1,
    pot: 0,
    crashPoint: null,
    crashMultiplier: null,
    seedHash: null,
    seed: null,
    startedAt: null,
    flightResumedAt: null,
    checkpointIndex: -1,
    currentCheckpointMultiplier: null,
    requiredBet: 0,
    bettingOpen: false,
    windowDeadlineAt: null,
    smallBlind: null,
    bigBlind: null,
    dealerPosition: null,
    players: state.players.map((p) => ({
      ...p,
      contributed: 0,
      isActive: false,
      folded: false,
      foldedAtMultiplier: null,
      lastAction: null,
      allIn: false,
      actedThisCheckpoint: false,
      cashoutMultiplier: null,
      busted: false,
      isPlaying: !p.isSittingOut,
    })),
    results: null,
  };
}

/**
 * Toggle a player between playing and sitting out (only in waiting phase).
 */
export function toggleSitOut(state, playerName) {
  if (state.phase !== "waiting") return state;

  return {
    ...state,
    players: state.players.map((p) =>
      p.name === playerName
        ? { ...p, isSittingOut: !p.isSittingOut, isPlaying: p.isSittingOut /* toggling to playing */ }
        : p,
    ),
  };
}
