/**
 * Crash Arena — Round State Machine (v2)
 *
 * Phases:
 *   waiting   — players opt in (PLAY) or opt out (SIT OUT)
 *   running   — the hand is live: everyone posted the flat ante and the
 *               crash curve climbs continuously; anyone can FOLD at any
 *               moment
 *   crashed   — multiplier hit crash point (or the hand folded out), the
 *               hand is over
 *   settling  — ranked payouts determined (fold-order rules), pot split
 *
 * This is the CLIENT-SIDE MIRROR of the server-authoritative hand state.
 * The server (API routes + src/lib/crash-poker) is the source of truth for
 * money; this module only renders and drives the Fold button. Every fold
 * is validated again on the server.
 *
 * Server-authoritative design (unchanged):
 *   • crashPoint is NEVER generated by the client — it is hidden until the
 *     crash, so the mirror carries `crashPoint: null` for the whole hand
 *     and the crash multiplier arrives only with the crash event (server
 *     broadcast / settled-round reveal).
 *   • seedHash is published before the hand; seed is revealed after for
 *     verification.
 *   • the ranked payouts are determined server-side (resolveHand) — this
 *     module mirrors the same fold-order ranking locally so the result
 *     modal can render before the authoritative results land; the server's
 *     numbers always win when serverResults are provided.
 */

// ── Factory ───────────────────────────────────────────────────────────────

/** Create initial round state from player list. */
export function createRoundState(players = [], roundNumber = 1) {
  return {
    phase: "waiting",
    roundNumber,
    pot: 0,
    carryOver: 0,
    // The crash point is server-only until the crash, so this stays null
    // during the hand; crashMultiplier is set from the crash event.
    crashPoint: null,
    crashMultiplier: null,
    seedHash: null,          // published before the hand (commitment)
    seed: null,              // revealed after the hand (for verification)
    startedAt: null,         // server epoch ms — aligns the shared curve
    // The curve is continuous from the hand start (no checkpoint pauses),
    // so flightResumedAt always equals startedAt.
    flightResumedAt: null,
    // Server-authoritative wall-clock deadline for the NEXT round start
    // (set when a hand settles) — every client counts down to it.
    nextRoundAt: null,
    players: players.map((p) => ({
      ...p,
      isPlaying: !p.isSittingOut,
      // ── v2 hand fields ────────────────────────────────────────────────
      contributed: 0,        // committed to the pot this hand (the ante)
      isActive: false,       // still in the hand
      folded: false,
      foldedAtMultiplier: null,
      lastAction: null,
      allIn: false,          // committed whole stack — can no longer fold
      // Legacy solo-crash field kept so existing UI reads don't crash.
      cashoutMultiplier: null,
      busted: false,
    })),
    results: null,
  };
}

// ── Transitions ───────────────────────────────────────────────────────────

/**
 * Start a new Crash Arena hand.
 *
 * @param state     Current round state (must be "waiting")
 * @param wager     Table wager — the flat ante everyone posts
 * @param crashPoint Server-authoritative crash point. Crash Arena keeps it
 *                   server-only until the crash, so pass null here — the
 *                   mirror stores it (null) and the crash multiplier
 *                   arrives with the crash event instead.
 * @param seedHash  SHA-256 hash of the hand seed (published before the hand)
 * @param seed      The hand seed (revealed after the hand for verification)
 * @param hand      Server hand snapshot: { wager, carryOver, startedAt,
 *                   flightResumedAt, contributions: [{ userId, amount,
 *                   allIn, isActive, foldedAtMultiplier }] }
 */
export function startRound(state, wager, crashPoint = null, seedHash = null, seed = null, hand = null) {
  if (state.phase !== "waiting") return state;

  if (crashPoint != null && (!Number.isFinite(crashPoint) || crashPoint < 1)) {
    console.warn("[roundSystem] startRound called with an invalid crashPoint — refusing.");
    return state;
  }

  const contributions = hand?.contributions || [];
  const carryOver = Number(hand?.carryOver ?? 0);

  const players = state.players.map((p) => {
    const isPlaying = p.isPlaying && !p.isSittingOut;
    const c = contributions.find(
      (x) => x.userId != null && p.userId != null && x.userId === p.userId,
    );
    // A player only enters the hand if they have an entry (a late joiner
    // mid-hand stays seated but sits out until the next hand).
    const inHand = Boolean(c) && isPlaying;
    const amount = c ? Number(c.amount) : 0;
    // Folded state for players who folded before this client synced.
    const wasFolded = Boolean(c?.isActive === false);
    return {
      ...p,
      balance: inHand ? Math.max(0, Number(p.balance) - amount) : p.balance,
      contributed: inHand ? amount : 0,
      isActive: inHand && !wasFolded,
      folded: wasFolded,
      foldedAtMultiplier:
        wasFolded && c?.foldedAtMultiplier != null
          ? Number(c.foldedAtMultiplier)
          : null,
      lastAction: inHand ? "ante" : null,
      allIn: inHand ? Boolean(c?.allIn) : false,
      cashoutMultiplier: null,
      busted: false,
    };
  });

  const pot = players.reduce((sum, p) => sum + Number(p.contributed), 0) + carryOver;

  return {
    ...state,
    phase: "running",
    pot,
    carryOver,
    crashPoint,
    crashMultiplier: null,
    seedHash,
    seed,
    startedAt: hand?.startedAt != null ? Number(hand.startedAt) : null,
    // Continuous curve — the flight never re-anchors, so flightResumedAt
    // equals the hand start.
    flightResumedAt:
      hand?.flightResumedAt != null
        ? Number(hand.flightResumedAt)
        : hand?.startedAt != null
          ? Number(hand.startedAt)
          : null,
    players,
    results: null,
  };
}

/**
 * Apply a fold to the local mirror. `server` carries the server-authoritative
 * numbers when provided (server is authoritative); otherwise the fold is
 * derived locally for the optimistic path.
 */
export function applyFold(state, playerName, multiplier = null, server = null) {
  if (state.phase !== "running") return state;

  const players = state.players.map((p) => {
    if (p.name !== playerName || !p.isActive || p.folded) return p;
    if (server) {
      // Apply the server-authoritative numbers directly.
      return {
        ...p,
        lastAction: "fold",
        isActive: false,
        folded: true,
        foldedAtMultiplier:
          server.foldedAtMultiplier != null
            ? Number(server.foldedAtMultiplier)
            : multiplier != null
              ? Number(multiplier)
              : null,
      };
    }
    // Optimistic local derivation (the server re-validates).
    return {
      ...p,
      lastAction: "fold",
      isActive: false,
      folded: true,
      foldedAtMultiplier: multiplier != null ? Number(multiplier) : p.foldedAtMultiplier,
    };
  });

  return { ...state, players };
}

/**
 * Mark the hand as crashed. Records the final multiplier. Every player still
 * active (not folded) busts.
 */
export function crashRound(state, crashMultiplier) {
  if (state.phase !== "running") return state;

  const players = state.players.map((p) => {
    if (p.isActive && !p.folded) {
      return { ...p, busted: true };
    }
    return p;
  });

  return {
    ...state,
    phase: "crashed",
    crashMultiplier,
    players,
  };
}

/**
 * Fold-order sort (local mirror of the server's latestFoldFirst): folded
 * players sorted with the LATEST fold first — highest multiplier, then the
 * fold recorded later in the action log, then roster order.
 */
function latestFoldFirstLocal(players) {
  const folds = players.filter((p) => p.folded && p.foldedAtMultiplier != null);
  return [...folds].sort((a, b) => {
    if (Number(a.foldedAtMultiplier) !== Number(b.foldedAtMultiplier)) {
      return Number(b.foldedAtMultiplier) - Number(a.foldedAtMultiplier);
    }
    return players.indexOf(b) - players.indexOf(a);
  });
}

/**
 * Settle the hand — rank the players by fold order and split the pot by
 * linear weights (local mirror of the server's resolveHand).
 *
 * Ranking: rank 1 = the sole survivor (fold-out) or the LAST player to fold
 * before the crash; then the remaining folders in reverse fold order. Crash
 * victims are unranked and get NOTHING. The pot (minus the 5% fee) is split
 * with rank r of R taking weight (R − r + 1). Nobody folded + crash → the
 * pot carries over.
 *
 * When `serverResults` is provided (the authoritative settle payload) it is
 * used verbatim — the server is authoritative.
 */
export function settleRound(state, serverResults = null) {
  if (state.phase !== "crashed" && state.phase !== "running") return state;

  const active = state.players.filter((p) => p.isActive && !p.folded && !p.busted);
  const folded = latestFoldFirstLocal(state.players);

  let results;
  if (serverResults) {
    results = serverResults;
  } else {
    // Local mirror of the server's rank settlement. The server is
    // authoritative — this only drives the modal until the authoritative
    // results land.
    const pot = Number(state.pot);
    let ranked = [];
    if (active.length === 1) {
      ranked = [active[0], ...folded];
    } else if (active.length >= 2 && folded.length > 0) {
      ranked = folded;
    }

    if (ranked.length === 0) {
      results = {
        winner: null,
        winnerMultiplier: null,
        wonByFold: false,
        payout: 0,
        fee: 0,
        payoutGross: 0,
        potDistributed: 0,
        carryOver: pot,
        payouts: [],
        foldedPlayers: [],
        bustedPlayers: state.players.filter((p) => p.busted).map((p) => p.name),
        activeAtCrash: state.players.filter((p) => p.busted).map((p) => p.userId),
      };
    } else {
      const R = ranked.length;
      const fee = Math.floor(pot * 0.05);
      const distributable = Math.round((pot - fee + Number.EPSILON) * 100) / 100;
      const sumWeights = (R * (R + 1)) / 2;
      const payouts = [];
      let accounted = 0;
      for (let i = 0; i < R; i += 1) {
        const weight = R - i;
        const amount =
          i === R - 1
            ? Math.round((distributable - accounted + Number.EPSILON) * 100) / 100
            : Math.round((distributable * weight) / sumWeights * 100 + Number.EPSILON) / 100;
        accounted += amount;
        payouts.push({
          userId: ranked[i].userId,
          name: ranked[i].name,
          rank: i + 1,
          amount,
        });
      }
      const winner = ranked[0];
      const wonByFold = Boolean(winner.folded);
      results = {
        winner: winner.name,
        winnerMultiplier: wonByFold ? winner.foldedAtMultiplier : null,
        wonByFold,
        payout: payouts[0].amount,
        fee,
        payoutGross: distributable,
        potDistributed: distributable,
        carryOver: 0,
        payouts,
        foldedPlayers: ranked
          .slice(1)
          .map((p) => ({ name: p.name, at: p.foldedAtMultiplier })),
        bustedPlayers: state.players.filter((p) => p.busted).map((p) => p.name),
        activeAtCrash: state.players.filter((p) => p.busted).map((p) => p.userId),
      };
    }
  }

  // Apply the ranked payouts to local balances so the sidebar matches the
  // modal (server numbers when provided), and attach display names to any
  // payouts for the result modal.
  const nameById = new Map(state.players.map((p) => [p.userId, p.name]));
  const resultsWithNames = results
    ? {
        ...results,
        payouts: (results?.payouts || []).map((r) => ({
          userId: r.userId,
          name: r.name ?? nameById.get(r.userId) ?? null,
          rank: Number(r.rank || 0),
          amount: Number(r.amount || 0),
        })),
        foldedPlayers: Array.isArray(results?.foldedPlayers)
          ? results.foldedPlayers
          : state.players
              .filter((p) => p.folded && p.name !== results?.winner)
              .map((p) => ({ name: p.name, at: p.foldedAtMultiplier ?? null })),
        bustedPlayers: Array.isArray(results?.bustedPlayers)
          ? results.bustedPlayers
          : state.players.filter((p) => p.busted).map((p) => p.name),
      }
    : null;
  const payoutByUserId = new Map(
    (resultsWithNames?.payouts || []).map((r) => [r.userId, Number(r.amount || 0)]),
  );
  const players = state.players.map((p) => {
    const credit = payoutByUserId.get(p.userId) ?? 0;
    return credit > 0 ? { ...p, balance: Number(p.balance) + credit } : p;
  });

  return {
    ...state,
    phase: "settling",
    results: resultsWithNames,
    players,
    carryOver: resultsWithNames?.carryOver ?? 0,
  };
}

/**
 * Move to the next hand — reset hand state, increment round number.
 * Seed/seedHash from the previous hand are cleared.
 */
export function nextRound(state) {
  if (state.phase !== "settling") return state;

  return {
    ...state,
    phase: "waiting",
    roundNumber: state.roundNumber + 1,
    pot: 0,
    crashPoint: null,
    crashMultiplier: null,
    seedHash: null,
    seed: null,
    startedAt: null,
    flightResumedAt: null,
    nextRoundAt: null,
    players: state.players.map((p) => ({
      ...p,
      contributed: 0,
      isActive: false,
      folded: false,
      foldedAtMultiplier: null,
      lastAction: null,
      allIn: false,
      cashoutMultiplier: null,
      busted: false,
      isPlaying: !p.isSittingOut,
    })),
    results: null,
  };
}

/**
 * Toggle a player between playing and sitting out (only in waiting phase).
 */
export function toggleSitOut(state, playerName) {
  if (state.phase !== "waiting") return state;

  return {
    ...state,
    players: state.players.map((p) =>
      p.name === playerName
        ? { ...p, isSittingOut: !p.isSittingOut, isPlaying: p.isSittingOut /* toggling to playing */ }
        : p,
    ),
  };
}