/**
 * Crash Arena — Round State Machine
 *
 * Phases:
 *   waiting   — players opt in (PLAY) or opt out (SIT OUT)
 *   running   — CrashEngine plays, players can cash out
 *   crashed   — multiplier hit crash point, round ends
 *   settling  — winner determined, pot distributed
 *
 * Server-authoritative design:
 *   • crashPoint is ALWAYS provided externally (never generated by the client).
 *   • seedHash is published before the round; seed is revealed after for verification.
 *   • winner & payout are determined server-side in settleRound.
 */

const PLATFORM_FEE = 0.05;

// ── Factory ───────────────────────────────────────────────────────────────

/** Create initial round state from player list. */
export function createRoundState(players = [], roundNumber = 1) {
  return {
    phase: "waiting",
    roundNumber,
    pot: 0,
    crashPoint: null,        // server-authoritative — set when round starts
    crashMultiplier: null,   // actual multiplier where crash occurred
    seedHash: null,          // published before round (commitment)
    seed: null,              // revealed after round (for verification)
    players: players.map((p) => ({
      ...p,
      isPlaying: !p.isSittingOut,
      cashoutMultiplier: null,
    })),
    results: null,
    carryOver: 0,
  };
}

// ── Transitions ───────────────────────────────────────────────────────────

/**
 * Start a new round.
 *
 * @param state      Current round state (must be "waiting")
 * @param wager      Round wager amount
 * @param crashPoint Server-authoritative crash point (required — client never decides)
 * @param seedHash   SHA-256 hash of the round seed (published before round)
 * @param seed       The round seed (revealed after round for verification)
 */
export function startRound(state, wager, crashPoint, seedHash = null, seed = null) {
  if (state.phase !== "waiting") return state;

  if (crashPoint == null || !Number.isFinite(crashPoint) || crashPoint < 1) {
    console.warn("[roundSystem] startRound called without valid crashPoint — server must provide this.");
    return state;
  }

  const playingPlayers = state.players.filter((p) => p.isPlaying && !p.isSittingOut);

  // Deduct wager from playing players
  const updated = state.players.map((p) => {
    if (p.isPlaying && !p.isSittingOut) {
      return { ...p, balance: Math.max(0, p.balance - wager), cashoutMultiplier: null, busted: false };
    }
    return { ...p, cashoutMultiplier: null, busted: false };
  });

  const pot = playingPlayers.length * wager + state.carryOver;

  return {
    ...state,
    phase: "running",
    pot,
    crashPoint,
    crashMultiplier: null,
    seedHash,
    seed,
    players: updated,
    results: null,
    carryOver: 0,
  };
}

/**
 * Record a player's cashout at a given multiplier.
 */
export function playerCashout(state, playerName, multiplier) {
  if (state.phase !== "running") return state;

  return {
    ...state,
    players: state.players.map((p) =>
      p.name === playerName && p.cashoutMultiplier === null
        ? { ...p, cashoutMultiplier: multiplier }
        : p,
    ),
  };
}

/**
 * Mark the round as crashed. Records the final multiplier.
 * Any playing player who didn't cash out gets busted.
 */
export function crashRound(state, crashMultiplier) {
  if (state.phase !== "running") return state;

  const players = state.players.map((p) => {
    if (p.isPlaying && !p.isSittingOut && p.cashoutMultiplier === null) {
      return { ...p, cashoutMultiplier: null, busted: true };
    }
    return p;
  });

  return {
    ...state,
    phase: "crashed",
    crashMultiplier,
    players,
  };
}

/**
 * Settle the round — determine winner and distribute pot.
 *
 * Winner = highest successful cashout.
 * Payout = pot − 5% platform fee.
 * If nobody cashed out, pot carries over to next round.
 */
export function settleRound(state) {
  if (state.phase !== "crashed") return state;

  const cashedOut = state.players.filter(
    (p) => p.isPlaying && !p.isSittingOut && p.cashoutMultiplier !== null && !p.busted,
  );

  let results;
  let carryOver = 0;

  if (cashedOut.length === 0) {
    carryOver = state.pot;
    results = {
      winner: null,
      winnerMultiplier: null,
      payout: 0,
      fee: 0,
      potDistributed: 0,
      allCashouts: [],
    };
  } else {
    cashedOut.sort((a, b) => (b.cashoutMultiplier || 0) - (a.cashoutMultiplier || 0));
    const winner = cashedOut[0];
    const fee = Math.floor(state.pot * PLATFORM_FEE);
    const winnerPayout = state.pot - fee;

    results = {
      winner: winner.name,
      winnerMultiplier: winner.cashoutMultiplier,
      payout: winnerPayout,
      fee,
      potDistributed: winnerPayout,
      allCashouts: cashedOut.map((p) => ({
        name: p.name,
        multiplier: p.cashoutMultiplier,
      })),
    };

    const players = state.players.map((p) => {
      if (p.name === winner.name) {
        return { ...p, balance: p.balance + winnerPayout };
      }
      return p;
    });

    return {
      ...state,
      phase: "settling",
      results,
      players,
      carryOver: 0,
    };
  }

  return {
    ...state,
    phase: "settling",
    results,
    carryOver,
  };
}

/**
 * Move to the next round — reset cashout state, increment round number.
 * Seed/seedHash from previous round are cleared.
 */
export function nextRound(state) {
  if (state.phase !== "settling") return state;

  return {
    ...state,
    phase: "waiting",
    roundNumber: state.roundNumber + 1,
    pot: 0,
    crashPoint: null,
    crashMultiplier: null,
    seedHash: null,
    seed: null,
    players: state.players.map((p) => ({
      ...p,
      cashoutMultiplier: null,
      busted: false,
      isPlaying: !p.isSittingOut,
    })),
    results: null,
  };
}

/**
 * Toggle a player between playing and sitting out (only in waiting phase).
 */
export function toggleSitOut(state, playerName) {
  if (state.phase !== "waiting") return state;

  return {
    ...state,
    players: state.players.map((p) =>
      p.name === playerName
        ? { ...p, isSittingOut: !p.isSittingOut, isPlaying: p.isSittingOut /* toggling to playing */ }
        : p,
    ),
  };
}
